### ISSUE TITLE
Jeux de données marqués comme non publiables

### ISSUE THREAD

**Issue by imallet** [etalab/geo.data.gouv.fr#1024]
Bonjour,

Certains jeux de données de geo.data.gouv.fr sont marqués comme non publiables sur data.gouv.fr avec la cause « Aucune distribution n’a été trouvée. »
La raison est que le flux WFS est indiqué comme « Non disponible »

Exemples : 
https://geo.data.gouv.fr/fr/datasets/e7c050ba9cb7126f3f04db442521e1556e3a15d9
https://geo.data.gouv.fr/fr/datasets/479f8aad95e5d9482001a709afff5f3742b5dcf7

or on constate, dans QGIS par exemple, que ces flux WFS sont bien disponibles.

Comment procéder pour relancer un test de disponibilité des ressources d’un jeu de données (et les rendre ainsi publiables dans data.gouv.fr) ?

**Comment by jdesboeufs** [comment]
Bonjour,

L'analyse de disponibilité des flux WFS est effectuée 1x par jour.
Néanmoins certains processus étaient bloqués, nous les avons relancé.

Il n'est actuellement pas possible de relancer un scan WFS à partir de l'interface, mais cela pourrait être une évolution (actuellement non financée).
