### ISSUE TITLE
Absence d'effet visuel à la publication

### ISSUE THREAD

**Issue by mariondr** [etalab/geo.data.gouv.fr#211]
Quand on sélectionne les jeux de données à publier et qu'on clique sur "Publier toutes les données", il ne se passe rien (visuellement).
Mais si on rafraîchit la page, les données sont bien publiées.

![capture d ecran 2017-01-20 a 12 16 16](https://cloud.githubusercontent.com/assets/25245240/22147769/8b20501e-df0a-11e6-9d36-dedd1213f82a.png)

**Comment by tmerlier** [comment]
Fixed by #212 Actualisation des jeux de données lors d'une publication
