### ISSUE TITLE
La carte ne s'affiche pas sur mobile

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/geo.data.gouv.fr#219]

**Comment by tmerlier** [comment]
Erreur 
-----
`Uncaught TypeError: Cannot read property '@@__symbol:hasInstance0.255180960590584371' of undefined`

**Comment by tmerlier** [comment]
@Flightan Une idée ?

**Comment by jdesboeufs** [comment]
C'est une erreur que t'as localement ou avec la prod ?

**Comment by tmerlier** [comment]
En prod et localement.

**Comment by Flightan** [comment]
Pour reproduire le bug:
 - Chome en mode responsive -> Selectionner iPhone 6
 - Rafraichir la page du dataset, afficher la carte

Cela semble provenir d'un polyfill de react-leaflet. Un peu dur a debugger.

**Comment by jdesboeufs** [comment]
Faut qu'on vire `react-leaflet`, ça ne marche pas avec `preact` et c'est
lourd.

**Comment by jdesboeufs** [comment]
Pas aujourd'hui évidemment.

**Comment by jdesboeufs** [comment]
Le polyfill `Symbol` de polyfill.io est défectueux.
Cf #249 #252
