### ISSUE TITLE
Utiliser les vrais catalogues en page d'accueil

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/geo.data.gouv.fr#227]
Actuellement les catalogues affichés sont en dur dans le code.

Afficher les 3 meilleurs catalogues (basé sur le « score »), permettre de trier la route /catalogs et limit=3.

**Comment by tusbar** [comment]
@jdesboeufs pour faire ça, il faudrait changer le endpoint `/api/geogw/catalogs` pour:

- Ajouter un mécanisme de pagination (limit=3)
- Implémenter le sort par score (https://github.com/etalab/geo.data.gouv.fr/blob/master/src/helpers/catalogs.js#L11)
