### ISSUE TITLE
Prise en charge aléatoire de la licence ODbL

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/geo.data.gouv.fr#244]
Jeu de données exemple : https://public.sig.rennesmetropole.fr/geonetwork/srv/fre/catalog.search#/metadata/548d87bc-4679-41d5-b396-c4b279651b62

Ce jeu de données est sous licence ODbL.

Or via le moteur de recherche on obtient "Non déterminé" :
https://inspire.data.gouv.fr/datasets/f6193e34f07591641358b8bd84109cddd9ab65e0

**Comment by jdesboeufs** [comment]
Autre exemple : https://inspire.data.gouv.fr/datasets/13dfa9f0c4df1db90bef06c0e0e38ac04cf2f931
=> LO

Catalogue source : https://public.sig.rennesmetropole.fr/geonetwork/srv/fre/catalog.search#/metadata/aa90d970-4b87-4a0d-b78c-9c4e270704fb
=> ODbL

**Comment by MaelREBOUX** [comment]
oui alors cet exemple est mauvais car les données sous-jacente sont bien en Licence Ouverte. Je m'en suis aperçu tout à l'heure.

Prendre cet exemple plutôt :  https://public.sig.rennesmetropole.fr/geonetwork/srv/fre/catalog.search#/metadata/3dafbf1e-37e7-4921-89f3-60505a656b3a

**Comment by jdesboeufs** [comment]
Ok en fait ce n'est pas un bug mais on n'extrait pas encore les informations du bloc Contraintes légales.
À suivre !

**Comment by jdesboeufs** [comment]
De nombreuses remontées de producteurs de données depuis le changement de nom.
Je prends le sujet tout de suite.
