### ISSUE TITLE
Téléchargement produisant un fichier vide

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/geo.data.gouv.fr#260]
Lorsque l'on essaie de télécharger ce jeu de données, cela produit un fichier vide.

[Adresse data.gouv.fr](https://www.data.gouv.fr/fr/datasets/referentiel-geographique-orthophotographie-mnt-vecteur-grand-poitiers-donnees-de-reference/)
[Adresse inspire.data.gouv.fr](https://inspire.data.gouv.fr/datasets/7e13a2f649402c063563570a937c0f4017cf86d8)

Première investigation à la main avec OGR : Succès.

**Comment by jdesboeufs** [comment]
Les données arrivent après plus de 20 secondes, ce qui déclenche le `timeout`.

**Comment by tusbar** [comment]
C’est lent mais ça fonctionne.

Un WFS proxy? :)
