### ISSUE TITLE
Erreur de visualisation d'une carte sur un jeu de données

### ISSUE THREAD

**Issue by mariondr** [etalab/geo.data.gouv.fr#263]
Sur ce jeu de données : https://inspire.data.gouv.fr/datasets/39b3290845f9eaa0d8ec74418a5cffbb12999d79

Quand je clique sur Visualiser la carte, un message d'erreur apparaît en rouge en haut de la carte : 
![capture d ecran 2017-02-02 a 16 52 08](https://cloud.githubusercontent.com/assets/25245240/22556614/12650422-e968-11e6-8cb3-7d9ade29d373.png)

**Comment by jdesboeufs** [comment]
Ces données sont vides. Les outils de visualisation devraient être assez robustes pour ne pas exploser bêtement.
