### ISSUE TITLE
Impossible de voir les filtres

### ISSUE THREAD

**Issue by mariondr** [etalab/geo.data.gouv.fr#268]
Impossible de sélectionner les filtres pour la recherche martinique, réunion, guadeloupe... 

https://inspire.data.gouv.fr/datasets?q=martinique

**Comment by tmerlier** [comment]
closed by #270 Correction de l'affichage des descriptions des jeux de données

**Comment by tmerlier** [comment]
closed by #270 Correction de l'affichage des descriptions des jeux de données
