### ISSUE TITLE
Jeux de données trop volumineux pour la pré-visualisation

### ISSUE THREAD

**Issue by tmerlier** [etalab/geo.data.gouv.fr#271]
Il peut arriver que certains jeux de données soient trop volumineux et par conséquent la pré-visualisation impossible car elle demande beaucoup trop de ressource au navigateur.

Exemple:
https://inspire.data.gouv.fr/datasets/5d0f6e2b5210632dd67820258cdcc29248d27627

**Comment by tmerlier** [comment]
Récupérer la taille du fichier afin d'afficher un warning serait un début.
Si on suppose que c'est au front de récupérer cette information avec `XMLHttpRequest` cela risque de poser des problèmes de cross origin.

**Comment by tusbar** [comment]
Il peut être intéressant de détecter des raisons pour lesquelles la preview prend trop de temps à s’afficher. Le nombre de features peut être un bon indicateur.

**Comment by tusbar** [comment]
Ça devrait être réglé avec le passage à mapbox-gl.

Cf. #616
