### ISSUE TITLE
Une organisation supprimée sur data.gouv n'est pas supprimée sur inspire.data.gouv

### ISSUE THREAD

**Issue by mariondr** [etalab/geo.data.gouv.fr#277]
La DRAAF Normandie a été supprimée sur data.gouv.fr (car doublon - mea culpa) mais pas sur inspire : https://inspire.data.gouv.fr/publication/589af1f988ee3873909b81a4

![capture d ecran 2017-02-08 a 11 44 25](https://cloud.githubusercontent.com/assets/25245240/22733921/0e5bd3c0-edf4-11e6-87c6-23e3af23dab0.png)

**Comment by jdesboeufs** [comment]
Déconnexion / reconnexion :)

**Comment by mariondr** [comment]
Ne marche pas chez moi malgré la déconnexion :(

**Comment by jdesboeufs** [comment]
Ah oui c'est normal, la suppression prend du temps (maximum quelques heures).
Mais considère que c'est supprimé.

**Comment by jdesboeufs** [comment]
Bloqué par opendatateam/udata#757
On peut contourner mais ce serait dommage.

**Comment by jdesboeufs** [comment]
udata 1.0 is warming up! 🔥

**Comment by jdesboeufs** [comment]
C'est corrigé en production sur data.gouv.fr.
