### ISSUE TITLE
Pollution de l'historique lors de la recherche

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/geo.data.gouv.fr#280]
Lorsque je clique par exemple sur un filtre dans une page Catalogue, j'arrive sur la recherche.
Si je clique sur le bouton "Précédent" de mon navigateur, je ne suis pas redirigé.
Par contre si je clique une fois de plus, c'est bon.

On peut voir qu'en fait l'URL est réécrite avec un échappement de caractères différent.

**Comment by tusbar** [comment]
Fixed by #398.
