### ISSUE TITLE
Évolution du bloc data.gouv.fr des jeux de données

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/geo.data.gouv.fr#299]
Le bloc actuel est affiché systématiquement sous cette forme :

<img width="394" alt="capture d ecran 2017-02-21 a 11 43 48" src="https://cloud.githubusercontent.com/assets/1231232/23161603/186b62cc-f82b-11e6-8d7b-38e943bc9744.png">

Dans le cadre de la refonte de la fiche "Jeu de données", il parait utile d'en revoir le fonctionnement.

Lors d'une discussion interne, voici ce qui a émergé :

- Cas 1 : le jeu de données est sur data.gouv.fr => on affiche le lien
- Cas 2 : le jeu de données n'est pas sur data.gouv.fr mais tout est vert => on affiche un message "Ce jeu de données peut être publié sur data.gouv.fr. Une action du producteur est nécessaire."
- Cas 3 : tout n'est pas vert => Ce jeu de données ne peut pas être publié sur data.gouv.fr. Plus d'infos (ça ouvre la liste actuelle)

**Comment by tmerlier** [comment]
Cas 1
-------
<img width="183" alt="capture d ecran 2017-02-21 a 12 21 38" src="https://cloud.githubusercontent.com/assets/7040549/23162860/4a0c63d0-f830-11e6-9340-2272767eb7e8.png">


Cas 2
-------
<img width="184" alt="capture d ecran 2017-02-21 a 12 21 26" src="https://cloud.githubusercontent.com/assets/7040549/23162865/53593be8-f830-11e6-91ac-a3d393483eb0.png">


Cas 3
-------
<img width="183" alt="capture d ecran 2017-02-21 a 12 21 12" src="https://cloud.githubusercontent.com/assets/7040549/23162870/5d6cacc8-f830-11e6-9d5f-71b38ef05e58.png">

Informations nécessaire
------------------------
- Lien vers la donnée sur data.gouv.fr

**Comment by jdesboeufs** [comment]
Il faut que j'avance sur #272

**Comment by jdesboeufs** [comment]
C'est pas sur master ni en prod !

**Comment by tmerlier** [comment]
Fixed by #327
