### ISSUE TITLE
Section Producteur du jeu de données

### ISSUE THREAD

**Issue by tmerlier** [etalab/geo.data.gouv.fr#301]
Informations nécessaires
-------------------------
- Producteur
- nombre de producteurs
- nombre de jeux de données

Prototype
----------
<img width="152" alt="capture d ecran 2017-02-24 a 15 49 57" src="https://cloud.githubusercontent.com/assets/7040549/23308082/3bdec6e6-faaa-11e6-9dcd-5805d5f8da9a.png">

**Comment by jdesboeufs** [comment]
Nombre de producteurs ?

**Comment by tmerlier** [comment]
Fixed by #327
