### ISSUE TITLE
Section Prévisualisation de la fiche de jeu de données

### ISSUE THREAD

**Issue by tmerlier** [etalab/geo.data.gouv.fr#302]
Informations nécessaires
-------------------------
- Toutes les pré-visualisations du jeu de données disponible

Prototype
-----------
<img width="149" alt="capture d ecran 2017-02-24 a 15 50 08" src="https://cloud.githubusercontent.com/assets/7040549/23308032/064e4f2e-faaa-11e6-906d-db7bd47de1bb.png">

**Comment by mariondr** [comment]
![vignette non disponible 3](https://cloud.githubusercontent.com/assets/25245240/23513169/6b698c58-ff63-11e6-9ef7-8392315860e6.jpg)
ça irait ?

**Comment by tmerlier** [comment]
Fixed by #327
