### ISSUE TITLE
Section Discussion de la fiche jeu de données

### ISSUE THREAD

**Issue by tmerlier** [etalab/geo.data.gouv.fr#304]
Informations nécessaires
-------------------------
- Conversations
- Auteurs

Prototype
----------
<img width="407" alt="capture d ecran 2017-02-24 a 15 50 41" src="https://cloud.githubusercontent.com/assets/7040549/23307977/d53af9aa-faa9-11e6-975a-f9c599b51ddd.png">

**Comment by jdesboeufs** [comment]
Ces informations sont accessibles via l'API de data.gouv.fr
Le pré-requis étant que les données doivent être publiées, car on a besoin de l'identifiant de publication.
Donc lié à #299

**Comment by tmerlier** [comment]
API Discussion data.gouv.fr =>`https://www.data.gouv.fr/api/1/discussions/?for={datasetId}`

**Comment by tmerlier** [comment]
Fixed by #327
