### ISSUE TITLE
Section Informations technique de la fiche jeu de données

### ISSUE THREAD

**Issue by tmerlier** [etalab/geo.data.gouv.fr#309]
Informations nécessaires
-------------------------
- [x] Fréquence de mise à jour
- [ ] Date de création
- [ ] Date de mise à jour
- [x] Type => `metadata.type`
- [ ] Échelle
- [ ] Résolution
- [x] Nom technique

Prototype
----------
<img width="409" alt="capture d ecran 2017-02-24 a 17 59 33" src="https://cloud.githubusercontent.com/assets/7040549/23312830/7b1fd58c-fabb-11e6-9b12-8daa204cf7f9.png">

**Comment by jdesboeufs** [comment]
Il faudrait mettre l'identifiant technique à cet endroit ;)

**Comment by jdesboeufs** [comment]
J'ai aussi un champ "Nom technique"

**Comment by tmerlier** [comment]
Fixed by #327
