### ISSUE TITLE
Material UI Warning

### ISSUE THREAD

**Issue by tmerlier** [etalab/geo.data.gouv.fr#31]
When a test need a `mount`

`Warning: Exception thrown by hook while handling onSetChildren: Invariant Violation: Expected onBeforeMountComponent() parent and onSetChildren() to be consistent (5 has parents 0 and 4).
    Invariant Violation: Expected onBeforeMountComponent() parent and onSetChildren() to be consistent (5 has parents 0 and 4).`

**Comment by jdesboeufs** [comment]
Fixed since we have rewritten tests.

**Comment by arperry** [comment]
What was the fix? I know this isn't StackOverflow, but this is literally the only reference to this issue I've been able to find.

**Comment by tmerlier** [comment]
We use this fix https://github.com/callemall/material-ui/issues/5078

```
export const mountWithContext = (node) => mount(node, {
  context: {
    muiTheme: getMuiTheme(),
  },
  childContextTypes: {
    muiTheme: React.PropTypes.object.isRequired,
  }
});
```
