### ISSUE TITLE
Libellé de lien incohérent lorsque inféré à partir de l'URL

### ISSUE THREAD

**Issue by JulienMeillon** [etalab/geo.data.gouv.fr#329]
Dans le bloc "Liens" de cette page : https://inspire.data.gouv.fr/datasets/26910bed84d28d0c530a71b99e63a27621e4bf7f le nom affiché pour une ressource ne correspond pas à ce qui est envoyé par le CSW.
Le lien est en effet tronqué et seul la partie après le dernier / est conservée.

Dans l'exemple de cette métadonnées (id : 2a145149-6ced-4a1f-a564-9167b8d1716f) voici ce qu'on trouve dans le catalogue d'orgine (Sextant) 
Name : http://www.rebent.org/index.php
Description : Site Web du Rebent : données et cartes interactives
Sur la "landing page" inspire.data.gouv on voit affiché "index.php" avec en revanche le lien qui est correct

Il faudrait au minimum avoir l'intégralité du lien et dans l'idéal, utiliser la description si celle-ci existe existe

**Comment by jdesboeufs** [comment]
En effet ça sent le bug. On regarde ça ASAP.

**Comment by jdesboeufs** [comment]
Désolé pour le délai.
Ce n'est pas un bug mais le comportement actuellement utilisé lorsque le nom de la ressource n'est pas renseigné, ce qui est le cas ici.

Prendre la contenu de la description est un choix qu'on ne peut pas faire à la légère puisqu'il s'agit d'une section contenant souvent beaucoup de texte.
Du coup nous extrayons le "nom du fichier" car c'est assez souvent pertinent.

Pourquoi ne renseignez-vous pas le champ Name ?
