### ISSUE TITLE
Impossible de publier sur data.gouv.fr

### ISSUE THREAD

**Issue by OrganisationCD45** [etalab/geo.data.gouv.fr#342]
Bonjour Inspire.data.gouv.fr,
Organisation Département du Loiret (CD45)
j'ai 44 jeux de données qui sont à publier dans mon organisation. J'ai sélectionné l'ensemble des jeux de données, et j'ai publié ces données depuis la plateforme hier mercredi 15 mars.
Ces jeux de données n'ont pas été publiés aujourd'hui 16 mars. Est ce un problème de méthode?
En vous remerciant pour votre retour

**Comment by jdesboeufs** [comment]
Bonjour,

La méthode est bonne, et la publication a en général lieu dans les secondes qui suivent.
Hier matin ce bug nous a été signalé par mail,
 et je pense l'avoir corrigé vers 17h30.

Peux-tu faire un nouvel essai ?

**Comment by OrganisationCD45** [comment]
Je viens de lancer la publication
[cid:image001.gif@01D29E37.4ABFF650]

Cordialement,
Jérôme BARET
Responsable systèmes d'informations géographiques du Loiret - SIGLO
PPGP-DS2I-Service aménagement numérique du territoire et SIG
Ligne fixe : 02 38 25 42 08

[http://signature.cg45.fr/logo_loiret.jpg]

Département du Loiret - 45945 Orléans
Centre de contacts : 02 38 25 45 45 - www.loiret.fr<http://www.loiret.fr/>

[http://signature.cg45.fr/logo_begood.png]
De : Jérôme Desboeufs [mailto:notifications@github.com]
Envoyé : jeudi 16 mars 2017 09:24
À : sgmap/inspire
Cc : BARET Jerome; Author
Objet : Re: [sgmap/inspire] Publication de données (#342)


Bonjour,

La méthode est bonne, et la publication a en général lieu dans les secondes qui suivent.
Hier matin ce bug nous a été signalé par mail,
et je pense l'avoir corrigé vers 17h30.

Peux-tu faire un nouvel essai ?

**Comment by OrganisationCD45** [comment]
Ok c’est passé
Merci

Cordialement,
Jérôme BARET
Responsable systèmes d'informations géographiques du Loiret - SIGLO
PPGP-DS2I-Service aménagement numérique du territoire et SIG
Ligne fixe : 02 38 25 42 08

[http://signature.cg45.fr/logo_loiret.jpg]

Département du Loiret - 45945 Orléans
Centre de contacts : 02 38 25 45 45 - www.loiret.fr<http://www.loiret.fr/>

[http://signature.cg45.fr/logo_begood.png]
De : Jérôme Desboeufs [mailto:notifications@github.com]
Envoyé : jeudi 16 mars 2017 09:24
À : sgmap/inspire
Cc : BARET Jerome; Author
Objet : Re: [sgmap/inspire] Publication de données (#342)


Bonjour,

La méthode est bonne, et la publication a en général lieu dans les secondes qui suivent.
Hier matin ce bug nous a été signalé par mail,
et je pense l'avoir corrigé vers 17h30.

Peux-tu faire un nouvel essai ?
