### ISSUE TITLE
Améliorer le contraste des métadonnées en header

### ISSUE THREAD

**Issue by davidbgk** [etalab/geo.data.gouv.fr#358]
<img width="823" alt="capture d ecran 2017-03-28 a 09 08 44" src="https://cloud.githubusercontent.com/assets/3556/24406359/2e034c40-1396-11e7-94a4-4478490b4938.png">

Testé avec [Colour Contrast Analyser](https://www.paciellogroup.com/resources/contrastanalyser/)

**Comment by jdesboeufs** [comment]
❤️ 

Help @tmerlier 
cc le _Chief Design Officer_ @Flightan

**Comment by tmerlier** [comment]
Rien à voir avec le schmilblick mais je vous laisse chercher l'erreur ;)
<img width="438" alt="capture d ecran 2017-03-28 a 16 55 31" src="https://cloud.githubusercontent.com/assets/7040549/24411939/703768f8-13d7-11e7-91ec-2188ab7b5800.png">

**Comment by tmerlier** [comment]
Le bleu est plus **vif** est le texte n'est plus en **gras**. Je trouve ça un peu plus net même si `Colour Contrast Analyser` n'aime toujours pas. Je penses que c'est la couleur de fond qui lui pose problème et comme il s'agit de la couleur "thème" du site, ça demande un peu plus de réflexion.

### Avant
<img width="830" alt="capture d ecran 2017-03-31 a 14 32 34" src="https://cloud.githubusercontent.com/assets/7040549/24550564/eb5c7c78-161e-11e7-908f-e12f022ffa19.png">

### Après
<img width="828" alt="capture d ecran 2017-03-31 a 14 32 16" src="https://cloud.githubusercontent.com/assets/7040549/24550562/eac6b242-161e-11e7-8edc-ffa524e37962.png">

**Comment by jdesboeufs** [comment]
Corrigé depuis la 2.2.0 :)
