### ISSUE TITLE
Éviter d'avoir des 3XX et 4XX sur les appels API/images

### ISSUE THREAD

**Issue by davidbgk** [etalab/geo.data.gouv.fr#359]
https://www.webpagetest.org/result/170328_QJ_11FM/1/details/#waterfall_view_step1

(les lignes jaunes et rouges)

**Comment by davidbgk** [comment]
Sinon sur la page cachée ça retente d'y accéder et ça ajoute un délai non négligeable à l'affichage https://www.webpagetest.org/result/170328_QJ_11FM/1/details/cached/#waterfall_view_step1

**Comment by jdesboeufs** [comment]
Alors les 404 sur les images c'est qu'on doit avoir une coquille quelque part.
401 sur le `/me`, comment le remplacerais-tu ? Calculer cette valeur côté serveur et l'injecter ?
Actuellement ce site est hébergé sur GitHub Pages.

Pour les 304 sur l'API, en quoi est-ce une mauvaise pratique ?

**Comment by davidbgk** [comment]
Pour les 401 : déjà identifier pourquoi il y a deux appels qui partent, ensuite en passant par GHPages je ne sais pas quelle flexibilité tu as côté serveur en effet :/

Pour la 304 : si je l'interprète bien tu viens aussi de récupérer les données donc je pense qu'elle pourrait être évitée.

**Comment by jdesboeufs** [comment]
On a aucune flexibilité puisque GH renvoie la page HTML brute.
Mais on peut très bien déployer le front sur notre serveur et maintenir le déploiement continu ;)
Ça permettra d'avoir une stratégie de cache des assets moins générique que celle imposée par GH.

OK j'avais pas compris que le rapport ne pointait les 304 qu'en cas de premier appel.
En effet il y a des doublons car nos composants React sont actuellement très bêtes.
Ça mérite investigation ça @tmerlier :D
