### ISSUE TITLE
Performances : essayer de scinder main.js

### ISSUE THREAD

**Issue by davidbgk** [etalab/geo.data.gouv.fr#360]
Le [JS principal met 2.5sec a être téléchargé mais surtout ensuite on perd 1 sec en exécution](https://www.webpagetest.org/result/170328_QJ_11FM/1/details/#waterfall_view_step1). Je me demande si le fait de télécharger/exécuter React à côté ne permettrait pas de gagner sur ces deux plans pour avoir un DOM interactive plus tôt.

**Comment by jdesboeufs** [comment]
Déjà on pourrait commencer par l'alléger au maximum le bundle de base.

Normalement on devrait pouvoir tourner sous [Preact](https://github.com/developit/preact), on l'a fait tourner en production pendant quelques jours avant de découvrir le bug #219.

Et sinon oui, du code splitting, c'est très souhaitable à ce stade.

**Comment by jdesboeufs** [comment]
Première itération importante avec #365

Par la suite on pourrait _lazy-loader_ les blocs `Chart.js` et `leaflet`, et/ou faire du splitting au niveau du routage.

**Comment by davidbgk** [comment]
Le [gain sur cette première itération est d'environ 1 sec](https://www.webpagetest.org/result/170329_5H_16VM/) 👍, je pense que l'on peut encore en gagner une en :

* sortant tout ce qui est react de vendors pour qu'il soit chargé en parallèle et puisse lancer l'exécution de app.js plus tôt
* virant/réduisant semanticui s'il est peu utilisé
* hébergeant Lato en local #368

Il y aura du boulot à faire sur la repeat view pour prefetch/load les 304 actuelles mais ça peut venir dans un 3e temps.

**Comment by davidbgk** [comment]
En splitant la CSS on a [gagné presque 0.5sec](https://www.webpagetest.org/result/170330_3Q_12PT/) 👍 

Prochaine étape : split du vendors.js car c'est lui qui est limitant.

Plus tard : jouer avec [prefetch/load](https://css-tricks.com/prefetching-preloading-prebrowsing/).

**Comment by davidbgk** [comment]
Pas encore digéré mais [Preload, Prefetch And Priorities in Chrome](https://medium.com/reloading/preload-prefetch-and-priorities-in-chrome-776165961bbf) donne des cas d'usages bien détaillés.

**Comment by davidbgk** [comment]
Aussi sur les [stratégies possibles sur les fonts](https://www.zachleat.com/web/comprehensive-webfonts/).

**Comment by tusbar** [comment]
On est pas mal là. Je ferme.

**Comment by tusbar** [comment]
On est pas mal là. Je ferme.
