### ISSUE TITLE
Héberger la police Lato en local

### ISSUE THREAD

**Issue by davidbgk** [etalab/geo.data.gouv.fr#368]
https://www.fontsquirrel.com/fonts/lato

Pour :

* plus de dépendance à Google
* davantage de latitude sur la stratégie de chargement (perfs)
* une dépendance à semanticui de moins

Contre :

* plus lent si on s'y prend mal :)

**Comment by jdesboeufs** [comment]
C'est juste un fichier TTF ?

**Comment by davidbgk** [comment]
Il faut ensuite le convertir en webfont tout en le tunant un peu https://www.fontsquirrel.com/tools/webfont-generator

À voir si les versions italique, gras sont utilisées aussi

**Comment by davidbgk** [comment]
Tiens il y a la version 2 directement en webfont aussi (je découvre) http://www.latofonts.com/lato-free-fonts/#download

**Comment by tusbar** [comment]
https://github.com/betsol/lato-font

**Comment by tusbar** [comment]
Ou alors on peut aussi drop Lato. :)

**Comment by jdesboeufs** [comment]
@tusbar on fait quoi du coup ici ?

**Comment by tusbar** [comment]
C’est tellement smart google fonts que c’est compliqué de faire mieux. Ils fallback sur des fonts plus light quand tu es sur un slow network, etc. 

Le mieux c’est d’utiliser une font native. :)

**Comment by jdesboeufs** [comment]
Le problème c’est quand avec notre position de site gouvernemental on ne
peut pas imposer aux utilisateurs d’être trackés par Google.

Et civiquement on devrait même tout mettre en oeuvre pour leur permettre de
ne pas l’être.

Le sam. 9 déc. 2017 à 11:14, Bertrand Marron <notifications@github.com> a
écrit :

**Comment by davidbgk** [comment]
La référence : https://www.zachleat.com/web/comprehensive-webfonts/

**Comment by jdesboeufs** [comment]
Follow-up: on a supprimé les fonts
#630
