### ISSUE TITLE
Amélioration du warning sur la fiche de jeu de données

### ISSUE THREAD

**Issue by tmerlier** [etalab/geo.data.gouv.fr#369]
La version actuel du `warning` présent sur les fiches de jeux de données est trop radicale et présente des problèmes de SEO.

<img width="849" alt="capture d ecran 2017-03-30 a 12 04 47" src="https://cloud.githubusercontent.com/assets/7040549/24499177/1960e412-1541-11e7-8917-45b26d5fd740.png">

Une version un peu plus discrète permettrai serait souhaitée.
### Exemples : 
<img width="845" alt="capture d ecran 2017-03-30 a 11 53 36" src="https://cloud.githubusercontent.com/assets/7040549/24498737/ba0754e8-153f-11e7-9f8d-4dbad8b1c4ba.png">

<img width="844" alt="capture d ecran 2017-03-30 a 11 52 49" src="https://cloud.githubusercontent.com/assets/7040549/24498738/ba21990c-153f-11e7-97c7-4d20e6359577.png">

**Comment by tmerlier** [comment]
@davidbgk un avis ou/et conseil concernant les exemples proposés ?

**Comment by davidbgk** [comment]
@tmerlier est-ce qu'il y aurait une date du moment où la donnée a été considérée comme étant obsolète?

**Comment by jdesboeufs** [comment]
Hélas non mais on pourrait à terme la déterminer puisqu'on stocke les versions successives des fiches.

**Comment by davidbgk** [comment]
Ok *ma* préférence va pour le bandeau, bonus s'il reste acroché en haut de page au scroll. À vérifier auprès d'utilisateurs ?
