### ISSUE TITLE
Problème d'affichage des liens en version mobile

### ISSUE THREAD

**Issue by tmerlier** [etalab/geo.data.gouv.fr#370]
<img width="303" alt="capture d ecran 2017-03-30 a 12 13 56" src="https://cloud.githubusercontent.com/assets/7040549/24499584/7cf2028a-1542-11e7-9547-a98469d02731.png">

**Comment by tmerlier** [comment]
@Flightan Tu aurais une idée de ce qui provoque ce problème ?

De plus on voit très clairement ici que le problème ne concerne que certains liens car ici un seul lien provoque l'erreur d'affiche et ce n'est pas dû à sa longueur puisque celui qui le précède s'affiche bien sur plusieurs lignes. 
<img width="277" alt="capture d ecran 2017-03-31 a 13 17 26" src="https://cloud.githubusercontent.com/assets/7040549/24548226/68f1fd58-1614-11e7-84cb-94121d3c419d.png">

**Comment by Flightan** [comment]
Probablement parce que ton lien n'a aucun séparateur ` ` espace ?
