### ISSUE TITLE
Pb de publication de fiche

### ISSUE THREAD

**Issue by jjacq44** [etalab/geo.data.gouv.fr#375]
Bonjour
La publication des fiches issues de sigloire via la passerelle semble ne pas fonctionner. J'ai bien coché les fiches que je souhaite publier et cliqué sur le bouton "publier les données sélectionnées" . Le message "publication en cours' apparait derrière chaque donnée mais rien de se passe a priori. J'avais déjà eu ce pb qui avait été résolu pour géoide, 
![ec_pb_publication_20170405](https://cloud.githubusercontent.com/assets/26918535/24693074/24d4a852-19dc-11e7-90a6-5ae3a816ab72.gif)

**Comment by tmerlier** [comment]
Bonjour @jjacq44 et merci pour votre participation !
J'atteste bien de votre problème. @jdesboeufs et moi-même allons rapidement nous pencher sur son origine.

**Comment by jdesboeufs** [comment]
Même problème rencontré par Grand Poitiers.

**Comment by jdesboeufs** [comment]
Je viens de tester et apparemment ça fonctionne à nouveau.
J'ai pu publier le jeu de données suivant : https://www.data.gouv.fr/fr/datasets/azi-de-la-riviere-la-maine-zones-inondables-en-loire-atlantique-et-vendee/

@jjacq44 Dis-nous si ça fonctionne de ton côté !

Encore merci.

**Comment by jjacq44** [comment]
Bonjour
La publication s'est bien faite (test fait sur 3 fiches). Par contre il y a deux soucis :
- certaines fiches ont disparu des données en attente de publication  : il y avait 72 fiches potentiellement publiables. Ce matin il n'y en avait plus que 59 (56 maintenant si on enlève les 3 que je viens de publier). Par ex je ne vois plus la fiche qui était pourtant proposé en publication la semaine dernière https://inspire.data.gouv.fr/datasets/4e3d2e636ccb247079c5ac0838c874594d9d13b1
- par ailleurs, il y a un pb d'affichage  : lorsqu'on a effectué une 1er publication de fiches et que l'on demande la publication de nouvelles fiches la mention "publication en cours" apparait sur les fiches cochées sans que l'on ait cliqué sur le bouton "publier les données sélectionnées". heureusement rien ne se passe.

**Comment by tmerlier** [comment]
Bonjour @jjacq44,

Concernant le problème d'affichage des publications, le correctif (#380) est en cours et ne devrait pas tarder à être corrigé.

**Comment by jdesboeufs** [comment]
Tout semble OK.
