### ISSUE TITLE
Proposition d'ajout d'un bouton de tri

### ISSUE THREAD

**Issue by jjacq44** [etalab/geo.data.gouv.fr#378]
Serait-il possible d'ajouter une possibilité de tri des fiches sur le titre de la fiche dans la passerelle au niveau de l'espace de publication ainsi que lorsqu'on affiche les fiches d'un service. Cela serait utile lorsqu'on veut sélectionner les fiches sur un thème par ex 'AZI de la vallée de l'Erdre' ou bien vérifier que l'on a pas perdu de fiches en comparant nos catalogues d'une part et les fiches sur la passerelle d'autre part.

**Comment by jdesboeufs** [comment]
@tmerlier je pense qu'on peut trier dans l'interface.
Tu prends ?

**Comment by tmerlier** [comment]
@jjacq44 c'est à moi que @jdesboeufs s'adressait. Je me lance dès que possible sur cette nouvelle fonctionnalité de tri qui est pour le moment inexistante sur inspire.data.gouv.fr

**Comment by tmerlier** [comment]
J'envisage de trier directement les fiches par ordre alphabétique à la place de mettre en place une option permettant de trier. Il n'y a aucune raison de préférer le chaos... non ?

Lié à #381
