### ISSUE TITLE
Tri des jeux de données par ordre alphabétique dans l'interface de publication

### ISSUE THREAD

**Issue by jjacq44** [etalab/geo.data.gouv.fr#383]
Bonjour
Le tri des fiches par ordre alphabétique dans la passerelle inspire ne fonctionne plus si l'on clique sur les boutons situés en bas de page pour aller aux pages suivantes (ex les liens  précédant, 2, 3, ..suivant etc).
Cordialement

**Comment by jdesboeufs** [comment]
Bonjour @jjacq44,

Le tri par ordre alphabétique n'a jamais été implémenté dans la partie publication mais c'est une excellente idée.

@tmerlier tu prends pour te remettre en jambe ?
