### ISSUE TITLE
Discussion non synchro avec data.gouv.fr

### ISSUE THREAD

**Issue by tmerlier** [etalab/geo.data.gouv.fr#386]
Une nouvelle discussion vient d'être ouverte aujourd'hui sur ce jeu de données: http://www.data.gouv.fr/fr/datasets/dnpb-chemins-des-parcs-departementaux/#discussion-58fb478888ee382830a89349

Problème, elle ne s'affiche pas sur Inspire.data.fr: https://inspire.data.gouv.fr/datasets/17eb5d1a81d30f3384aa051224daa2645ba75e2b

**Comment by jdesboeufs** [comment]
Deux problèmes ici :
* Le jeu de données pense qu'il n'est pas publié sur data.gouv.fr
* Le bloc Discussions s'affiche quand même, mais aucune requête n'est faite

**Comment by tusbar** [comment]
Visiblement la donnée liée par @tmerlier  n’est pas la même sur data.gouv.fr et geo.data.gouv.fr.

Le problème du bloc de discussion qui s’affiche ne semble plus être d’actualité.
