### ISSUE TITLE
Date de mise à jour de la fiche : il y a 47 ans

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/geo.data.gouv.fr#389]
Ticket soumis par courriel :

Salut Jérôme, 

un peu étonnant la mention « mis à jour il y a 47 ans » sur la page de ce jeu de données: https://inspire.data.gouv.fr/datasets/c4c1006bb3e5d1f576de26a836c6402d65b8e1bd :)

bon week-end à toi

**Comment by tmerlier** [comment]
@jdesboeufs Le problème semble semble être réglé. `Close` ?
