### ISSUE TITLE
appariemment de noms de producteur de données

### ISSUE THREAD

**Issue by mkazmiers** [etalab/geo.data.gouv.fr#394]
Bonjour,

Nous publions des données ouvertes pour le compte de la "CA - Durance Luberon Verdon Agglomération (DLVA)". Préalablement, j'ai demandé à un admin chez eux de créer le compte de l'organisation sur data.gouv.fr. Je m'attendais donc à trouver celle-ci dans la liste des producteurs auxquels je peux associer le CRIGE PACA. Ce n'est pas le cas.

En effet, en jettant un coup d'oeil, celui-ci a créé son organisation au nom de "Durance Luberon Verdon Agglomeration" :  https://www.data.gouv.fr/fr/organizations/durance-luberon-verdon-agglomeration/.
J'imagine que modifier le nom de l'organisme dans notre catalogue ou sur data.gouv.fr changerait la donne dans notre cas...
Mais plus généralement, cela pose la question des différentes orthographes que l'on peut trouver pour désigner une même structure.

Est-il prévu un outil pour résoudre ce genre de conflit ou des bonnes pratiques à adopter par rapport à la publication des noms d'organismes?

Bonne journée,
Mathieu

**Comment by jdesboeufs** [comment]
T'as-t'il invité en tant qu'administrateur de leur organisation ?

**Comment by tusbar** [comment]
Il faut être ajouté en tant qu’administrateur de l’organisation sur data.gouv.fr.
