### ISSUE TITLE
npm install + npm start does not work

### ISSUE THREAD

**Issue by thom4parisot** [etalab/geo.data.gouv.fr#395]
I read the README and noticed it mentioned yarn.
However I deliberately tried the install with `npm@5` to see how it would perform:

```bash
npm i -g npm@latest
npm start
npm install
```

I have the following error in the console when connecting on http://localhost:3000:

```
Uncaught TypeError: _this.setState is not a function
    at eval (webpack:///./~/react-router/es/Router.js?:117:15)
    at eval (webpack:///./~/react-router/es/createTransitionManager.js?:235:13)
    at eval (webpack:///./~/react-router/es/createTransitionManager.js?:90:11)
    at done (webpack:///./~/react-router/es/AsyncUtils.js?:76:19)
    at eval (webpack:///./~/react-router/es/AsyncUtils.js?:82:7)
    at getComponentsForRoute (webpack:///./~/react-router/es/getComponents.js?:8:5)
    at eval (webpack:///./~/react-router/es/getComponents.js?:32:5)
    at eval (webpack:///./~/react-router/es/AsyncUtils.js?:81:5)
    at Array.forEach (native)
    at mapAsync (webpack:///./~/react-router/es/AsyncUtils.js?:80:9)
```

However if I do the following, all is good – the inspire page shows up with the search engine:

```bash
yarn
npm start
```

Question: what can be so different between npm and yarn install? Are there stuff automatically done by yarn after fetching packages?

**Comment by jdesboeufs** [comment]
`yarn install` will use the `yarn.lock` file whereas `npm install` will try to resolve modules versions from scratch.

**Comment by thom4parisot** [comment]
Agreed with the use of `yarn.lock` — I tried deleting the yarn.lock file and running `yarn install`, the aforementioned problem happens even both with npm and yarn.

It seems that the current `yarn.lock` contains a set of package versions I cannot replicate again with a fresh install, either with yarn and npm.

I wonder if you have an idea of which package could cause this issue and if so, I could try to pin the correct package version(s) in `package-lock.json`.

**Comment by jdesboeufs** [comment]
I will look at this but I think it must be react-router or one of its
friends (as usual).
Le mer. 14 juin 2017 à 17:33, Thomas Parisot <notifications@github.com> a
écrit :

**Comment by rr-pro** [comment]
Hello,

About the "Uncaught TypeError: _this.setState is not a function", I got it also after an npm-only install and start.

I managed to get rid of it by following : 
 https://github.com/developit/preact-compat/issues/47#issuecomment-294662594 

i.e. I created src/create-react-class.js file containing : 

```
const { createClass } = require('preact-compat');
module.exports = createClass;
```

Robert
