### ISSUE TITLE
publication données bloquée

### ISSUE THREAD

**Issue by mkazmiers** [etalab/geo.data.gouv.fr#399]
Bonjour,

J'ai essayé de publier des données (Sections cadastrales dept84 et ocsolreg du CRIGE).
La publication est notée "Publication en cours"...
![image](https://user-images.githubusercontent.com/16324693/27860266-107e1cd4-617c-11e7-8bb1-5953267d30e0.png)
Mais ne semble pas suivi d'effets.
Quand je rafraichi, le process semble  revenu à son point de départ et la donnée n'est pas notée comme publiée.

Je ne réussi donc pas à publier les données depuis mon compte. Une idée d'où cela peut venir?

**Comment by jdesboeufs** [comment]
Est-ce que tu parles de cette organisation ?
https://www.data.gouv.fr/fr/organizations/crige-paca/

**Comment by tusbar** [comment]
Ça devrait être réglé désormais.
