### ISSUE TITLE
SetState

### ISSUE THREAD

**Issue by tmerlier** [etalab/geo.data.gouv.fr#4]
If a page change is performed while loading `Catalogs` component data is not finished, a series of error appears.

This is due to the promises that are not completed.

```
warning.js:36 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Catalog component.
```

**Comment by tmerlier** [comment]
À tester:
----------
 https://hashnode.com/post/preact-with-redux-and-react-router-cit04gxwy0jxg8k53wodpyl3m

**Comment by jdesboeufs** [comment]
Fixed
