### ISSUE TITLE
SIGLOIRE et passerelle Inspire - Dysfonctionnements

### ISSUE THREAD

**Issue by jjacq44** [etalab/geo.data.gouv.fr#470]
Bonjour
Le lien entre Sigloire et la passerelle semble ne plus bien fonctionner. En effet, dans l'interface d'administration de la passerelle il est indiqué que 49 jeux sont publiés sur data.gouv.fr pour la DDTM44. Hors, lorsque je vais sur data.gouv.fr ne n'en trouve que 22. A priori les fiches issues de sigloire n'apparaissent plus sur data.gouv.fr.  On constate sur une fichier inspire de la passerelle issues de sigloire 
(par ex : https://inspire.data.gouv.fr/datasets/4e3d2e636ccb247079c5ac0838c874594d9d13b1) il est indiqué que le téléchargement est indisponible alors que les données sont bien téléchargeables depuis Sigloire ainsi que depuis le lien de téléchargement présent sur la fiche inspire (https://catalogue.sigloire.fr/rss/atomfeed/atomdataset/e738b4c0-d393-11de-b18a-00004f6210c3)
J'ai d'autres jeux de données Sigloire qui devraient normalement être proposés sur la passerelle en publication sur data.gouv.fr. Hors il n'y a rien en attente de publication.
Cela peut-il être dû à la nouvelle version mise en place sur la plateforme sigloire le 12/6/2017 ?
Merci de votre éclairage.

**Comment by jjacq44** [comment]
Bonjour

A priori non. La "synchro" s'est remise en place effectivement tout 
récemment. Par contre j'ai les fiches issues de sigloire qui ont été 
publiées automatiquement sans que j'ai eu à activer la publication. Je 
ne sais pas si cela est normal. Peut-être cela a t-il été nécessaire de 
votre coté pour rétablir la publication entre sigloire et la passerelle.
La publication avec mon compte reste t -elle toujours possible ?

Par contre je vois dans la liste des catalogues moissonnées que Sigloire 
est référencé deux fois : une fois avec le catalogue SIGLOIRE(local) et 
l'autre fois avec SIGLOIRE. Seul le catalogue SIGLOIRE(local) doit être 
moissonné car lui seul contient les données publiées sur la plateforme. 
Le catalogue SIGLOIRE contient non seulement le catalogue 
SIGLOIRE(local) mais aussi les données moissonnées par la plateforme 
Sigloire  sur Géo-IDE (donc cela fait doublon avec Géo-ide).
Cela sera-t-il corriger ?

A demain

Bien cordialement


Joëlle JACQ

DDTM44 / Responsable du pôle géomatique

Mission Observation, Prospective, Evaluation, Développement Durable
Direction départementale des territoires et de la mer de Loire-Atlantique
10, boulevard Gaston Serpette
BP 53606 - 44036 NANTES CEDEX 1
Tel : 02.40.67.24.56, Fax : 02.40.67.24.09
Courriel : joelle.jacq@loire-atlantique.gouv.fr
Plateforme régionale Sigloire pour le partage des données géographiques : https://catalogue.sigloire.fr/

Le 11/12/2017 à 14:52, "> Jérôme Desboeufs (par Internet, dépôt 
bounces+848413-e81c-joelle.jacq=loire-atlantique.gouv.fr@sgmail.github.com)" 
a écrit :

**Comment by jdesboeufs** [comment]
Plusieurs corrections ont été effectuées et la publication est de plus en plus automatique.
Concernant SIGLOIRE local et global, en effet le catalogue global ne sera bientôt plus dans la liste mais toujours moissonné pour des raisons de traçabilité interne.
