### ISSUE TITLE
Problème de synchro des ressources avec data.gouv

### ISSUE THREAD

**Issue by tportier** [etalab/geo.data.gouv.fr#502]
Salut,

On a détecté un bug. Pour ce jeu de données : https://inspire.data.gouv.fr/datasets/2708a0f86c72349b2d7fdbfee26869012f481f2b

La donnée source est un ZIP contenant plusieurs SHP. Sur la passerelle INSPIRE, les liens de téléchargement des différentes ressources sont bonnes. Par contre sur data.gouv, les différents liens de téléchargement pointent tous sur la première ressource "INFO_SURF" : https://www.data.gouv.fr/fr/datasets/plu-de-baraqueville/

**Comment by jdesboeufs** [comment]
Ce n'est plus le cas apparemment.
@tportier tu valides ?

**Comment by tportier** [comment]
Si, c'est toujours le cas. On ne peux télécharger que la couche INFO_SURF sur data.gouv

**Comment by jdesboeufs** [comment]
Je confirme le bug.

L'analyseur a bien ouvert le ZIP et détecté les 3 couches, mais les URL générées pour ces couches sont parfaitement identiques et n'incluent pas le nom de la couche.
Conséquence : le module d'extraction prend la première couche trouvée.

Reste à comprendre pourquoi les URL générées ne comprennent pas le nom de la couche.

**Comment by tusbar** [comment]
Les 3 SHP sont bien disponibles : https://geo.data.gouv.fr/en/datasets/2708a0f86c72349b2d7fdbfee26869012f481f2b.
