### ISSUE TITLE
Résolution d'URL dans les médias sociaux

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/geo.data.gouv.fr#504]
Aujourd'hui l'approche SPA sans rendu côté serveur ne permet pas d'afficher une carte pertinente dans les médias sociaux qui n'exécutent pas le code JavaScript (Twitter, Slack…).

Il faudrait a minima que la brique côté serveur génère les métadonnées adéquates dans la page HTML.

**Comment by tusbar** [comment]
Sort of duplicate of https://github.com/etalab/inspire/issues/336. :)
