### ISSUE TITLE
Description des jeux de données coupée

### ISSUE THREAD

**Issue by tmerlier** [etalab/geo.data.gouv.fr#508]
Lorsque que la description d'un jeu de données est trop longue, le texte est coupé.
<img width="895" alt="capture d ecran 2017-10-12 a 11 05 56" src="https://user-images.githubusercontent.com/7040549/31488245-5bcf5b8a-af3d-11e7-9d45-0fb37fbe31d4.png">

**Comment by jdesboeufs** [comment]
@tusbar tu peux jeter un oeil ? Que tout le lancement de la v2.2 ne dépende pas que de @tmerlier :)

**Comment by tusbar** [comment]
@jdesboeufs j’ai déjà essayé quelques solutions pour ça cet après-midi et je pense que c’est très lié à #509 en fonction de la solution qu’on décide d’adopter.

Il y a plusieurs possibilités :

1. Garder un overflow brut comme aujourd’hui, en ajoutant un blur en bas pour montrer quand c’est tronqué (on peut également ajouter un « voir plus », qui au final envoie sur la fiche complète)

2. Reproduire un comportement comme en prod aujourd’hui, avec un bouton « voir plus » qui extend la description et l’affiche entirèrement dans la preview.

3. Supprimer tout markup du markdown, afficher un maximum de 3 ou 4 lignes (variable en fonction du viewport) ou X caractères avec un simple overflow et `text-overflow: elipsis`.

Enfin, sur les petits devices, la description (et les tags) ne sont pas (ou très peu si pas trop petit) affichés, je pense qu’il faudrait un minimum.

Le 3. me semble le plus « clean », mais on perd toute structure sur le markdown (on peut garder juste les `\n`).

@jdesboeufs, @tmerlier, vous en pensez quoi ?

**Comment by tusbar** [comment]
Je pense qu’à terme il faudra le générer (cleaner) côté serveur ce paragraphe, puis le stocker.

Mai oui j’aime bien l’idée du premier paragraphe avec une limite de characteres/lignes en plus pour pas que ce soit trop long.

👍

**Comment by jdesboeufs** [comment]
On pourra faire ce qu’on veut côté serveur quand on aura véritablement rénové certaines briques, dont `link-proxy`. Sinon ça ouvre trop de chantiers simultanés pour notre petite équipe...
