### ISSUE TITLE
Problème d'actualisation des ressources en téléchargement

### ISSUE THREAD

**Issue by TERMEPhilippe** [etalab/geo.data.gouv.fr#552]
la donnée 
https://geo.data.gouv.fr/datasets/01dacb1cf6cec9be021b5de94b7e27b1d142cbae
propose en téléchargement des liens obsolètes (depuis juin 2017).
Il n'y a donc pas actualisation des informations malgré les moissonnages opérationnels.
Voir les liens des téléchargement vers la fiche originelle
https://catalogue.sigloire.fr/geonetwork/srv/fre/catalog.search;jsessionid=D4DE3063ADD2E51FC2B817C9E67CFACD#/metadata/1dc8d7f7-7952-4e41-a14c-ad9d1fc4b03e

**Comment by jdesboeufs** [comment]
Bonjour Philippe,

3 fiches différentes pour ce jeu de données existent dans notre base de données :
- les deux (identiques) de SIGLOIRE (global et local)
- celle de GEOPAL
- celle du Géocatalogue nationale (obsolète)

Celle qui a été sélectionnée par notre algorithme est celle de GEOPAL : http://www.geopal.org/geonetwork/srv/fre/find?uuid=1dc8d7f7-7952-4e41-a14c-ad9d1fc4b03e

Les trois fiches ont la même date de révision, ce qui n'est pas normal puisqu'elles sont différentes : 2017-03-17T13:02:02Z
Cela signifie que les modifications qui ont été faites dans ou par PRODIGE n'ont pas incrémenté la date de révision, déclenchant la propagation de variantes.
Notre algorithme, basé sur cette date, ne sait donc pas choisir.

**Comment by jdesboeufs** [comment]
Il y a donc deux portes de sortie :
- concevoir une stratégie de sélection plus élaborée au niveau de notre plateforme (moyen terme)
- forcer la mise à jour de la fiche en la modifiant dans SIGLOIRE

Dans tous les cas il me parait important de pouvoir comprendre pourquoi votre plateforme a produit ces variantes sans modifier la date.

**Comment by jdesboeufs** [comment]
La suite dans #570.

**Comment by TERMEPhilippe** [comment]
Bonjour Jérôme,
effectivement, Prodige a évolué et nos catalogues ont migré.
Une des évolutions concerne notamment l'utilisation d'un certificat et 
les url sont désormais en https.
Cela ne se voit pas pour l'accès aux fiches de métadonnées puisqu'une 
redirection a été mise en place mais par contre c'est visible dans 
l'accès aux ressources externes (flux atom, wxs).
Cette modification n'a pas été répercutée sur la date d'actualité de la 
métadonnée et j'ai fait remonté de problème au comité coordinateur de 
Prodige.
Dans notre cas, je pense que Geopal n'a pas actualisé son flux de 
moissonnage et diffuse donc des données obsolètes de Sigloire.
Je confirme donc le besoin que tu as retranscrits dans le ticket 570 de 
mieux prendre en compte le catalogue source dans l'alimentation de 
geo.data.gouv.fr

Bonne journée

Philippe

Le 10/12/2017 22:17, > Jérôme Desboeufs (par Internet, dépôt 
bounces+848413-dba8-philippe.terme=developpement-durable.gouv.fr@sgmail.github.com) 
a écrit :
