### ISSUE TITLE
Erreur de projection

### ISSUE THREAD

**Issue by mariondr** [etalab/geo.data.gouv.fr#554]
Erreur de projection sur la fiche du jeu de données ["Chemins et itinéraires de randonnées (PDIPR)" du département de Seine-Saint-Denis](https://geo.data.gouv.fr/datasets/a02a60437f08e77d6a1c7d474c03e8aa77ea3378)

Quand on clique sur Téléchargements -> Visualiser
La Seine-Saint-Denis se retrouve en Espagne 

![capture d ecran 2017-11-16 10 26 46](https://user-images.githubusercontent.com/25245240/32883792-a8232228-cab8-11e7-9856-8e3b74140ef3.png)

https://geo.data.gouv.fr/datasets/a02a60437f08e77d6a1c7d474c03e8aa77ea3378

**Comment by tusbar** [comment]
Cela semble réglé.

<img width="835" alt="screen shot 2018-04-16 at 2 47 56 pm" src="https://user-images.githubusercontent.com/166147/38809842-378abdb6-4185-11e8-83bc-7d01e31ed896.png">
