### ISSUE TITLE
Associer un flux CSW à un compte utilisateur

### ISSUE THREAD

**Issue by imallet** [etalab/geo.data.gouv.fr#555]
Bonjour,
Dans l'ancienne plateforme https://inspire.data.gouv.fr mon compte 'imallet@grandlyon.com' était associé au flux CSW du catalogue de la Métropole de Lyon, et je pouvais ainsi lancer manuellement un moissonnage.
J'ai l'impression que ce n'est plus le cas dans la nouvelle plateforme https://geo.data.gouv.fr/
(ou bien je n'ai pas trouvé comment accéder à cette fonctionnalité... ;-(

En effet : en étant loguée avec mon compte dans https://geo.data.gouv.fr/ , je n'ai aucune fonctionnalité associée au catalogue GrandLyon Smart Data, hormis la consultation de ce dernier.

Merci d'avance de votre éclairage
Cordialement,
I Mallet

**Comment by jdesboeufs** [comment]
Bonjour,

La fonctionnalité de publication existe toujours, on y arrive via le menu en haut de page.
 
<img width="1275" alt="capture d ecran 2017-11-16 a 13 26 27" src="https://user-images.githubusercontent.com/1231232/32891168-ecb7ca38-cad1-11e7-9765-fbcc37d2bfaf.png">

Le moissonnage est désormais automatique et a lieu toutes les nuits.

Nous restons à votre disposition.

**Comment by imallet** [comment]
Bonjour Jérôme,
Merci de votre réponse rapide et OK : je viens de tester, ça marche !
Cordialement,
I Mallet
