### ISSUE TITLE
Modifier l'intitulé d'un catalogue

### ISSUE THREAD

**Issue by imallet** [etalab/geo.data.gouv.fr#556]
Bonjour,

Pourriez-vous modifier l'intitulé du catalogue 'GrandLyon Smart Data' (obsolète) en 'Data Grand Lyon'
ou bien m'indiquer comment le faire si mon compte imallet@grandlyon.com dispose des droits correspondant sur ce catalogue dans la plateforme https://geo.data.gouv.fr/

Merci d'avance
I.  Mallet

**Comment by jdesboeufs** [comment]
Une telle interface de gestion n'existe pas encore et n'est pas prévue à court terme.
Nous faisons les changements à la demande.

Je m'en charge ASAP.

**Comment by imallet** [comment]
D'accord, pas de souci
Merci d'avance

**Comment by jdesboeufs** [comment]
C'est fait.
Le moteur de recherche et les différentes métriques associées risquent de présenter des résultats incohérents pendant au maximum 2h.

**Comment by imallet** [comment]
Parfait, merci !
