### ISSUE TITLE
Impossible de publier une donnée en attente de publication

### ISSUE THREAD

**Issue by mkazmiers** [etalab/geo.data.gouv.fr#560]
Bonjour,

Testé auj le workflow de publication sur data.gouv d'un dataset qui n'est pas de mon organisation.
i) associé le producteur "Région PACA" à mon compte
ii) demandé à publier la donnée "Région PACA - EPCI [..]" depuis la liste des données en attente de publication
iii) la publication mouline (icône de chargement apparaît) mais ne semble pas effective.

Est-ce que cette fonctionnalité de publication pour le compte d'une autre organisation est activée?

Merci, bonne journée
Mathieu

**Comment by jdesboeufs** [comment]
Bonjour @mkazmiers,

As-tu pu refaire un essai ?
La fonctionnalité fonctionne depuis presque toujours.

**Comment by mkazmiers** [comment]
Bonjour @jdesboeufs,

Je rencontrai et rencontre tjrs le même problème que @jerbou , cf. #581 
J'ai essayé avec la même donnée que dans ce premier post, Région PACA-EPCI... -> il ne se passe rien.

Un problème lié à la fiche de méta en elle-même?

Merci

Mathieu

**Comment by jdesboeufs** [comment]
En fait la passerelle INSPIRE n'est pas admin de l'organisation CRIGE PACA.

**Comment by mkazmiers** [comment]
OK.
Et comment faire pour que ce soit le cas?

**Comment by jdesboeufs** [comment]
C'est probablement que quelqu'un l'a enlevée.
Je peux rétablir la situation.

**Comment by jdesboeufs** [comment]
C'est bien sur l'organisation CRIGE PACA que tu veux publier ces données ?

**Comment by mkazmiers** [comment]
Oui pour commencer

**Comment by mkazmiers** [comment]
Après je voulais publier pour d'autres organisations auxquelles le CRIGE PACA est associé

**Comment by jdesboeufs** [comment]
Mais tu es bien Admin de ces organisations sur data.gouv ?
On peut s’appeler rapidement demain si tu veux.

Le mer. 31 janv. 2018 à 16:38, mkazmiers <notifications@github.com> a
écrit :

**Comment by mkazmiers** [comment]
Même admin CRIGE j'arrivais pas à publier.
Par contre, je n'étais pas admin des autres, non -> hum. Forcément, ça ne risquait pas de fonctionner. j'essaierai avec le CD05, on a une 50aine de datasets en opendata qui feront un bon usecase

**Comment by mkazmiers** [comment]
retesté après https://github.com/etalab/data.gouv.fr/issues/59, suis admin de CRIGE-PACA et essaie de publier une donnée d'ocsol dont CRIGE-PACA est propriétaire.
Ca ne fonctionne pas.

**Comment by mkazmiers** [comment]
Any idea?

**Comment by baltrian** [comment]
Idem pour la publication des [données géo-ide de la DGALN](https://geo.data.gouv.fr/fr/search?availability=yes&q=DGALN&organization=DGALN%20(Direction%20G%C3%A9n%C3%A9rale%20de%20l%27Am%C3%A9nagement%2C%20du%20Logement%20et%20de%20la%20Nature)) via l'organisation ministère cohésion des territoires de data.gouv.fr (avec profil admin)

**Comment by jdesboeufs** [comment]
OK il y a vraisemblablement un problème persistant.
Je regarde cet après-midi.

**Comment by mkazmiers** [comment]
Bonjour @jdesboeufs,

J'ai ressayé de publier des données pour le compte du Département des Hautes-Alpes qui publie des données en opendata sur le catalogue CRIGE PACA.
Dans l'ordre, on a créé l'organisation Département des Hautes-Alpes par l'utilisateur membre, il a le statut d'admin.

Dans geodatagouv, on a ensuite ajouté le catalogue du CRIGE à la liste des catalogues de l'organisation. On a associé l'organisation "Département 05" à l'organisation "Département des Hautes-Alpes". Ca nous affiché 52 jdd en attente de publication. On essayé d'en publier plusieurs, en même temps ou une par une : échec. Au clic sur "Publier les données", ça mouline brièvement et ça revient au point de départ, à la liste des données toutes décochées.

Même problème que pour la publication crige...
On a pourtant réussi strictement la même opération avec l'organisation "SMO PACA THD". Peux-tu jeter un oeil stp?

Bonne journée,
Mathieu

**Comment by jerbou** [comment]
Bonjour,

@mkazmiers , de notre côté, je publie les jdd de la DREAL...
Jusqu'à aujourd'hui ;), Il y avait six de données en attente de publication.
Ex de jdd : 
https://geo.data.gouv.fr/fr/datasets/1c8f03c47d2d0e635a70077467b5465d768db49e
Ce sont les premiers jeux (avec plusieurs couches SIG) pour une même fiche MD dataset ?
geo.data n'indique pas de problème pour publier.

Au push (interface de publication, aprés avoir cliqué sur les tout selection 
Une erreur imprévue s'est produite est apparue. Pourtant le temps d'écrire le ticket sur github, tout a bien été publié :)

@jdesboeufs : Un de ces quatres, tu pourrais nous un peu dire un peu plus, sur l'action de publication ?
On pourrait peut être mieux qualifier les éventuelles remontées de bug, si on monte en puissance avec les partenaires sur la publication via geo.data / IDG.

Bonne journée,
Jérôme B

**Comment by tusbar** [comment]
Ça devrait être réglé.

Quelques petits soucis visuels peuvent encore arriver dans l’interface de publication, on va améliorer ça.
