### ISSUE TITLE
Suppression et changement de nom de catalogue

### ISSUE THREAD

**Issue by jpotel** [etalab/geo.data.gouv.fr#562]
Bonjour
Je n'ai pas trouvé de fonction pour changer le nom du catalogue de mon organisation et la suppression d'un catalogue qui n'est plus utilisé.
Serait-il possible pour vous de supprimer le catalogue DREAL Haute-Normandie qui n'existe plus et renommer le catalogue DREAL Basse-Normandie et DREAL Normandie.
Merci

**Comment by jdesboeufs** [comment]
Bonjour,

Le catalogue DREAL Haute-Normandie n'est en effet plus actif.
Par contre il contenait de jeux de données qui peuvent encore être téléchargés à ce jour mais qui ne sont présents dans aucun autre catalogue.
Par exemple : https://geo.data.gouv.fr/fr/datasets/44a1d3e700305b641308e1c4b41c0303d6762c4f

Nous allons donc plutôt archiver ce catalogue, dès que la fonctionnalité sera disponible.

Le catalogue DREAL Basse Normandie sera renommé ASAP.

**Comment by jdesboeufs** [comment]
Le renommage a été effectué.
Le contenu du catalogue risque d'être perturbé pendant au maximum 2h le temps que les données soient intégralement réindexées.

**Comment by jpotel** [comment]
merci
