### ISSUE TITLE
Fiche en double sur data.gouv.fr suite mauvaise manip lors du catalogage

### ISSUE THREAD

**Issue by jjacq44** [etalab/geo.data.gouv.fr#573]
Bonjour
Persiste toujours ce problème de fiche en double pour le même jeu de donnée (signalé depuis de longue date). Il s'agit des fiches :
https://www.data.gouv.fr/fr/datasets/plan-de-prevention-des-risques-naturels-pprn-de-la-loire-aval-dans-lagglomeration-nantaise-zones-reglementees-en-loire-atlantique/

 https://www.data.gouv.fr/fr/datasets/zones-reglementees-du-plan-de-prevention-des-risques-naturels-pprn-de-la-loire-aval-dans-lagglomeration-nantaise-en-loire-atlantique/

Cette deuxième fiche est dûe à une erreur de nommage de la couche qui avait été faite de façon non conforme au standard (et dont les donnée n'ont jamais été disponibles) et une mauvaise manip lors du catalogage quand on a voulu rectifier.

Il conviendrait de supprimer la 2ième fiche car les utilisateurs auront toujours un message d'erreur lors du téléchargement. De plus je n'ai plus la main sur cette fiche dans le catalogue original.

**Comment by tusbar** [comment]
Les données en question n’existent plus.
