### ISSUE TITLE
Publier via geo.data.gouv ? Bug à l'action du producteur sur publier les données

### ISSUE THREAD

**Issue by jerbou** [etalab/geo.data.gouv.fr#581]
Bonjour,

Nous avons sur idéobfc, 4 données en attente de publication pour une organisation (DREAL BFC).
Sur la fenetre idoine, en faisant tout selectionner, puis publier les données, je ne reçois pas de confirmation de l'action.
Le bouton change en publication, l'utilisateur est en attente d'une confirmation, (cela se faisant de mémoire avec l'animation du bouton publication, puis un refresh de la page, pour montrer les données publiées sur data.gouv.fr).
Après plusieurs essais, les 4 données sont toujours en attente de publication...
Help ! ;)

D'avance Merci,

**Comment by jerbou** [comment]
Bonjour,

Je reproduis le problème. Y a t il des opérations de maintenance sur la fonctionnalité de publication de la passerelle qui bloque ou autre chose ?

D'avance Merci,

**Comment by mkazmiers** [comment]
Bonjour,

Même phénomène.

Idem je n'arrive pas à publier des données pour le CRIGE PACA depuis la passerelle.
L'organisation CRIGE PACA est associée à mon compte. Je sélectionne les données d'ocsol à publier. Je clique sur Publier des données -> rien ne se passe, sauf que la sélection est "décochée".

Mathieu

**Comment by jdesboeufs** [comment]
En fait il semblerait que le compte application "Passerelle Inspire" ait été retiré des administrateurs de l'organisation CRIGE PACA.

**Comment by jdesboeufs** [comment]
@jerbou c'est corrigé, la file d'attente était bloquée depuis un moment.
À surveiller de notre côté.

Je ferme. N'hésites pas à réouvrir si tu remarques à nouveau le problème.

**Comment by jerbou** [comment]
Merci  @jdesboeufs Je regarde au prochain moissonnage.
@mkazmiers C'est ok pour le tien ?

**Comment by jerbou** [comment]
Bonjour,

Je reproduis à nouveau le problème. (le bouton 
@jdesboeufs, tu peux voir de quoi il en retourne ?
J'ai essayer une autre fois et le message suivnat s'est affiché : 
'Une erreur imprévue s'est produite'

Merci d'avance !

**Comment by mkazmiers** [comment]
(tu peux rouvrir le ticket @jerbou ?)

**Comment by jerbou** [comment]
Je ne crois pas pouvoir "rouvrir" les tickets, si c'est cela veut passer le tag open.
Pas grave, @jdesboeufs l'a rouvert, et je confirme que les données BFC ont été publié ce vendredi.
A tester on aura d'autres datas qui viennent.

A plus,

**Comment by tusbar** [comment]
Ça devrait être bon maintenant !
