### ISSUE TITLE
Catalogue GéoGuyane

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/geo.data.gouv.fr#585]
Nous avons reçu une demande de référencement du catalogue GéoGuyane.

URL du flux CSW : https://www.geoguyane.fr/geonetwork/srv/fre/csw-geoguyane
Page d'accueil de la plateforme : https://www.geoguyane.fr

Un catalogue GéoGuyane est déjà référencé mais il s'agit du catalogue du portail, contenant plus que les données administrées localement.

**Comment by tusbar** [comment]
https://geo.data.gouv.fr/en/catalogs/53889f4f280d0d8d3c2ede67
