### ISSUE TITLE
Plus de moissonnage de Géo-IDE

### ISSUE THREAD

**Issue by rr-pro** [etalab/geo.data.gouv.fr#595]
Bonjour,
depuis 13 jours le moissonnage de Géo-IDE est en échec.
Du côté du serveur, le point de moissonnage CSW répond normalement.

En regardant les logs, je constate que le process s'arrête immédiatement après une requête GetRecords
?maxRecords=20&elementSetName=full&resultType=results&request=GetRecords&startPosition=4421&typeNames=gmd%3AMD_Metadata&outputSchema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&service=CSW&version=2.0.2

La réponse à cette dernière requête est assez volumineuse (~ 770 Ko), il y a peut être un débordement de capacité quelque part ?

Merci

R Rivière

**Comment by jdesboeufs** [comment]
J'ai relancé et c'est passé.
C'est plus lié à un problème de charge chez nous, et d'engorgement de file d'attente.
