### ISSUE TITLE
Données CSV affichées comme ZIP sur data.gouv.fr

### ISSUE THREAD

**Issue by jerbou** [etalab/geo.data.gouv.fr#624]
Hello,

@jdesboeufs Merci encore pour la qualité des échanges de ces deux derniers jours 

Nous avons un acteur qui utilise une solution de catalogage pour documenter des données géo ISNPIRE mais également dorénavant des données ouvertes non géo. 
J'avais échangé avec la personne ressource si passer par la passerelle geo.data était cohérent pour ces données, cela passe bien techniquement comme le montre le dataset suivant : 
https://www.data.gouv.fr/fr/datasets/liste-des-prenoms-des-nouveaux-nes-ville-de-belfort-2016/

Le format initial est du csv, est correctement restitué sur geodata mais pas sur data.gouv (zip).

Pourriez vous regarder de votre côté, pour cette conversion a lieu.

tout cela, parce que dans notre portail régional, nous avons un possibilité de prévisu tabulaire qui fonctionne avec du csv mais pas avec du zip.
Comme par exemple :
http://databfc.fr/bfc/visualisation?id=6c9584cb-dbb5-4bbd-9994-11e605a740c8&serveur=https://data.databfc.fr

Merci de votre éclairage, et désolé par avance si je n'ai pas posté sur data.gouv/issues/

Bonne journée à vous,

**Comment by jdesboeufs** [comment]
C'est le nom du format qui est faux, mais c'est bien un CSV.
Je regarde pour corriger.

**Comment by jerbou** [comment]
Est-ce que c'est une correction manuelle que tu va faire ou pas ?
Car j'ai recommandé à la personne en charge de l'ouverture de reformer la data pour obtenir 1 fiche (1 dataset) avec 3 ressources pour 3 millésimes différents.
Donc cette fiche va pt être effacée dans le futur.
Le truc est de bien voir ou se passe ce nom de format faux.

**Comment by jdesboeufs** [comment]
C'est un bug chez nous.

**Comment by jerbou** [comment]
Ok, ca sera cool pour les catalogue isog . J'en ai parlé avec Julien à Foss4G qui a fait au mieux pour pluguer le catalogue.

Tu me diras quand même si ca te va de pusher des tableur csvs à travers un point csw ...

La fonctionnalité est agile pour les admin finaux ; un seul catalogue à gérér (inspire ou pas) 
Quid de data.gouv ?

Je vais transmettre l'info' et faire tache d'huile auprés des acteurs locaux :)

A plus,

**Comment by amerour** [comment]
Bonjour,
J'ai créé la fiche globale des prénoms, on ne voit sur data.gouv que le fichier csv de 2014 
https://www.data.gouv.fr/fr/datasets/liste-des-prenoms-des-nouveaux-nes-ville-de-belfort/
alors que sur geodata, on voit els autres fichiers
++

**Comment by jdesboeufs** [comment]
@amerour merci pour le signalement. Il s'agissait d'un bug chez nous que je viens de corriger.

@jerbou il n'y a pas de problème à publier des CSV ou autres données non géographiques via les CSW.
Il faut juste nous signaler quand certains formats ne sont pas reconnus.

**Comment by jerbou** [comment]
@jdesboeufs Merci, C'est une information que je transfert à Yorick (il le sait déja probablement).
Il faut bien le lien de téléchargement directement accessible (https//... /tableur.csv) pour le catalogue source. OK pour isogeo, a voir pour d'autres IDG...

**Comment by Guts** [comment]
Et hop, une bonne chose de faite :)

**Comment by jerbou** [comment]
Hello,

Le partenaire local constate que data.gouv.fr présente toujours le format en tant que zip.
La repasse aurait elle enlevé la correction ? @jdesboeufs 

A plus,

**Comment by jdesboeufs** [comment]
Le bug "format ZIP" n'est lui pas corrigé, c'est pour ça que j'ai laissé cette issue ouverte ;)

**Comment by jerbou** [comment]
Bonjour,

@amerour m'a relancé sur ce bug "format ZIP".
L'api d'isogeo amène au téléchargement de la data déposé, mais c'est toujours affiché en tant que ZIP.
Ex :
https://services.api.isogeo.com/csw/p/bzlhtql2KAg1yNc-J0_TPt0ZNxvX0/resources/26cf446a00e849c7a2e364e5260b4a01/links/b0a30763c68140a3a294cc2d213d491f.bin
amène bien à l'ouverture fichier / téléchargement du ficheir déposé (un csv), 

mais c'est toujours tagué comme ZIP.

**Comment by tusbar** [comment]
Tous ces problèmes devraient désormais être réglés ! 🙌
