### ISSUE TITLE
Donnée en licence ODbL marquée comme "licence ouverte"

### ISSUE THREAD

**Issue by rr-pro** [etalab/geo.data.gouv.fr#626]
Bonjour,

dans Géo-IDE quelques données sont publiées sous licence ODbL.
Par exemple : 
http://catalogue.geo-ide.developpement-durable.gouv.fr/catalogue/srv/fre/catalog.search#/metadata/fr-120066022-jdd-bafc1e31-5900-4130-a7ba-3246e98c9ef6

Or elle apparaît sur geo.data.gouv.fr comme sous licence ouverte.
https://geo.data.gouv.fr/fr/datasets/7eef071160bfbbddb5ba781d031393daab350335

Sauf erreur, l'export ISO côté Géo-IDE suit les recommandations CNIG pour l'expression de la licence (section `MD_LegalConstraints`)
Pouvez vous de votre côté implémenter la reconnaissance de cette licence ?

Merci

**Comment by jdesboeufs** [comment]
Cette licence est en principe reconnue. Je vais regarder pourquoi ce n'est pas le cas ici.

**Comment by jdesboeufs** [comment]
Notre implémentation actuelle attends aussi une balise `<gmd:useConstraints>` avec la valeur `license`.
Voici un exemple d'implémentation qui fonctionne :

```xml
<gmd:resourceConstraints>
  <gmd:MD_LegalConstraints>
    <gmd:useLimitation>
      <gco:CharacterString>
        Réutilisation libre sous réserve de la mention obligatoire suivante : "source : réseau STAR septembre 2015 - Rennes Métropole"
      </gco:CharacterString>
    </gmd:useLimitation>
    <gmd:useLimitation>
      <gco:CharacterString>
        Licence ODbL 1.0 http://www.data.rennes-metropole.fr/notre-demarche/licence-odbl-ville-de-rennes-et-rennes-metropole/
      </gco:CharacterString>
    </gmd:useLimitation>
    <gmd:accessConstraints>
      <gmd:MD_RestrictionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions"/>
    </gmd:accessConstraints>
    <gmd:useConstraints>
      <gmd:MD_RestrictionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#MD_RestrictionCode" codeListValue="license"/>
    </gmd:useConstraints>
    <gmd:otherConstraints>
      <gco:CharacterString>
        Pas de restriction d’accès public
      </gco:CharacterString>
    </gmd:otherConstraints>
  </gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
```

Si notre approche est trop stricte, nous pouvons essayer de l'ajuster.

**Comment by rr-pro** [comment]
OK, vu, il nous manque en effet la balise `<gmd:useConstraints>` qui est bien spécifiée par le guide CNIG.
A nous de voir comment corriger cela. Merci !
