### ISSUE TITLE
Checklist for open data publication

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/geo.data.gouv.fr#63]
In each dataset page, we should have a section with:
- Publication state (published or not)
- Remote link

We may have a checklist to help data producers to investigate why their data could not be published as open data:
- License detection
- Data availability
- At least one eligible producer

**Comment by jdesboeufs** [comment]
# Point de situation

## Détection de licence

L'information se trouve dans `metadata.license`:
- `fr-lo` => Licence Ouverte => OK !
- `odbl` => Licence ODbL v1 => OK !
- `undefined` => Non détectée => Pas OK !

## Disponibilité de la donnée

L'information se trouve dans `dataset.distributions`, qui est un tableau:
- Si le tableau contient au moins une entrée avec `available: true` alors le jeu de données est disponible => OK !
- Sinon, le jeu de données n'est pas disponible => Pas OK !

## Producteur

L'information se trouve dans `organizations`:
- Si le tableau contient au moins un élément => OK !
- Si le tableau est vide => Pas OK !

Évidemment ce n'est qu'un début.

**Comment by tmerlier** [comment]
Fixed by #95
