### ISSUE TITLE
[Discussion] Ajout Commentaire geo.data / data.gouv

### ISSUE THREAD

**Issue by jerbou** [etalab/geo.data.gouv.fr#635]
Hello, 

On voit votre nouvelle livraison, ou l'on peut directement voir les commentaires sur geo.data / data.gouv.

Par contre, je me suis connecté via le site data.gouv, je constate le bouton Envoyer un commentaire avec fenetre active.

Sur geodata
https://geo.data.gouv.fr/fr/datasets/09a62430493b20e0f3fdbc1ae23b91c263a4e2b5
Je vois que l'on peut répondre directement, et on me demande de me connecter le bouton Se connecter est sans effet.
Du WIP, je suppose :)

**Comment by jdesboeufs** [comment]
Normalement ça fonctionne bien depuis plusieurs mois.
Ce qui a changé c'est que maintenant la "connexion" est plus rapide donc ça peut être perturbant.

Tu peux faire un nouvel essai ?

**Comment by jerbou** [comment]
Ok, en mode rigoureux et sur un autre navigateur, ca marche :
arrive sur geo.data / clic sur se connecter / login, mpd.

Par contre je ne vois pas mon commentaire sur geo.data (gestion de cache entre geo.data et data.gouv ?)
J'ai fait un reply sur data.gouv.fr sur le dataset précédemment cité.
Est-ce que je fais un autre ticket ?

**Comment by jdesboeufs** [comment]
L'interface n'est pas exactement la même, il faut déplier ta réponse en cliquant sur "Une réponse".

On va discuter avec @taniki pour converger vers la même chose :)

**Comment by jerbou** [comment]
Arf désolé, j'avais pas vu !
