### ISSUE TITLE
Lien de téléchargement sur les foramts HS sur firefox

### ISSUE THREAD

**Issue by jerbou** [etalab/geo.data.gouv.fr#639]
Hello,

J'ai remarqué sur firefox 60.0.2 (64 bits) sur la fiche suivante que je ne peux télécharger de fichiers à partir des boutons GeoJSON, SHP/L93
https://geo.data.gouv.fr/fr/datasets/d03ed7760600490b62ef5af152fd36f72867fab4
même aprés avoir vidé le cache, et rafraichir plusieurs fois.

Alors que sur Chrome 67.0.3396.87, cela fonctionne.

De plus et en bonus, firefox kickof 
https://github.com/etalab (echec de la connexion sécurisée ?)

A la prochaine,

**Comment by jdesboeufs** [comment]
Je n'arrive pas reproduire :(
