### ISSUE TITLE
Mise à jour fiche (contenu et ressources) inopérante aprés Moissonnage ?

### ISSUE THREAD

**Issue by jerbou** [etalab/geo.data.gouv.fr#669]
Bonjour,

On me demande de publier une données spécifique en Opendata.

La fiche MD source :  
https://www.ideobfc.fr/geonetwork/srv/fre/catalog.search#/metadata/2ee4f989-40f6-4f3e-8747-80d3e4147601
avec trois ressources publiées en WFS et un csv joint

Son équivalent sur geo.data date un peu (et le contenu éditoriale de la fiche est différent)
https://geo.data.gouv.fr/fr/datasets/12e9508d5673f3f4cd319e54dea76d53de1f0e85
date un peu, et la plateforme précise que "Ce jeu de données ne peut pas être publié sur data.gouv.fr."
Aucune licence n’a été spécifiée + pas de disponibilité.

J'ai relancé un moissonnage de IDéO Local, j'ai laissé faire la tache prés d'une heure.
Je relance ma rechercher en croyant que la fiche sous geo a été mise à jour et sera prête à publier.
Ce n'est pas le cas, la fiche de geo.data m'indique qu'il est pas possible de publier.

Du coup, est-ce que vous pourriez vous si le moissonnage avec IDéO a été correctement effectué ?
Voir si la synchronisation peut se "compléter" c'est à dire annuler et remplace le contenu de la fiche geo, la mise en cache des couches WFS et que la publication sur data.gouv.fr peut être réalisé.

D'avance Merci et à bientôt,

**Comment by tusbar** [comment]
Bonsoir @jerbou,

Ce jeu de données est maintenant publiable : https://geo.data.gouv.fr/fr/datasets/12e9508d5673f3f4cd319e54dea76d53de1f0e85.
