### ISSUE TITLE
Plus de moissonnage de Géo-IDE ?

### ISSUE THREAD

**Issue by rr-pro** [etalab/geo.data.gouv.fr#684]
Bonjour,
Géo-IDE n'a plus été moissonnée depuis 18 jours à en croire 
https://geo.data.gouv.fr/fr/catalogs/539ebc2f1a66c51a7c52f5a3

De plus le bouton "Moissonner ce catalogue" y est grisé.

Pouvez vous regarder ?

Merci

R Rivière

**Comment by jdesboeufs** [comment]
J'ai relancé.

**Comment by rr-pro** [comment]
Merci Jérôme !

Apparemment c'est retombé il y a 8 jours.

Cordialement

Robert

**Comment by jdesboeufs** [comment]
Quelle merde ce moissonneur. Heureusement que je suis en train de le réécrire :)

J'ai relancé.

**Comment by jdesboeufs** [comment]
Cette fois j'ai scripté la relance le lendemain en cas d'échec.

**Comment by rr-pro** [comment]
Ok, maintenant il se relance mais finit "en échec" sans autre info :-)
