### ISSUE TITLE
Refine dataset metrics

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/geo.data.gouv.fr#69]
We have 3 _dataset_ metrics but for now computed on the whole _record_ stock:

- Percentage of open datasets
- Percentage of downloadable datasets
- Distribution of data types

**Comment by Flightan** [comment]
Regrouper les charts:
Concernant les records 
<img width="369" alt="screen shot 2016-11-07 at 13 35 25" src="https://cloud.githubusercontent.com/assets/1475946/20058041/1d46723a-a4ef-11e6-8aca-fc321b310780.png">
<img width="395" alt="screen shot 2016-11-07 at 13 35 22" src="https://cloud.githubusercontent.com/assets/1475946/20058043/21499600-a4ef-11e6-9e80-1fd97a44e872.png">

Concernant les dataset
<img width="326" alt="screen shot 2016-11-07 at 13 35 20" src="https://cloud.githubusercontent.com/assets/1475946/20058047/297a95fe-a4ef-11e6-9844-29c73dc1d17e.png">
<img width="699" alt="screen shot 2016-11-07 at 13 35 13" src="https://cloud.githubusercontent.com/assets/1475946/20058050/2dab1a4a-a4ef-11e6-8708-57fcb83f64f5.png">

**Comment by jdesboeufs** [comment]
L'essentiel du boulot a été fait avec la PR #77 et le commit https://github.com/inspireteam/geogw/commit/56d6d82922f930b24a67fc754971e5a82daec68a.
Il reste à gérer le type `nonGeographicDataset`.
