### ISSUE TITLE
Erreur de moissonnage pour IDéO BFC  (local)

### ISSUE THREAD

**Issue by jerbou** [etalab/geo.data.gouv.fr#745]
Bonjour,

Le moissonnage avec le CSW IDéO bfc local semble en échec, pourriez vous regarder cela.
https://geo.data.gouv.fr/fr/catalogs/5538ecf3e92d07976f61877b
Comme je constate que l'ensemble des autres plateformes utilisant le même outil, je me pose des questions, cela provient probablement de notre point...

Un événement sur l'ouverture des données a lieu Vendredi à Besançon, et on aimerait bien valoriser les données ouvertes déposées sur la plateforme IDéO.

D'avance Merci,

**Comment by jdesboeufs** [comment]
Hélas je pense que ça venait de chez nous 😢
