### ISSUE TITLE
Identification de la Disponibilité de donnée par geo.data ? Deux datasets posent question

### ISSUE THREAD

**Issue by jerbou** [etalab/geo.data.gouv.fr#788]
Hello, 

Un acteur @amerour nous fait remonter une incompréhension :

Les deux dataset suivants sont reconnu comme indisponibles, et donc non publiables
https://geo.data.gouv.fr/fr/datasets/b051b6d4c046a95bd95297386aa8d4873cce7a8d
https://geo.data.gouv.fr/fr/datasets/2618737ea9c1f5b462ff8494fde4b3d29b1354ee

Les data est disponible via un lien comme par exemple :
https://services.api.isogeo.com/csw/p/bzlhtql2KAg1yNc-J0_TPt0ZNxvX0/resources/bfcea880f1f44e4fadb9a78573e44ef9/links/139af8c9ce574de9bade5142bd0d50eb.bin
Ils sont décrits dans la fiche.

D'autres datasets sont reconnus comme disponibles comme
https://geo.data.gouv.fr/fr/datasets/254798ab260f7c6aeb4889bbc13f1c2ea9ac4b82

Une petite explication de texte serait la bienvenue.
D'avance Merci !

**Comment by jerbou** [comment]
Merci pour la rapidité !
Désolé je n'avais pas constaté la différence de formats...

Je fonce évoquer le format ouvert vers l'acteur local ;
en rappelant le bon principe de publier en csv ;) et non pas en format propriétaire.

Merci et à + !

**Comment by amerour** [comment]
Bonjour,
Et merci pour votre réponse, je vais transformer les fichiers xls en xlsx.
Cordialement

MEROUR Anthony
Direction des Systèmes d'Information
GRAND BELFORT Communauté d'Agglomération
03 70 04 80 17



De : Bertrand Marron [mailto:notifications@github.com]
Envoyé : mardi 23 octobre 2018 11:25
À : etalab/geo.data.gouv.fr
Cc : Anthony MEROUR; Mention
Objet : [NEWS] Re: [etalab/geo.data.gouv.fr] Identification de la Disponibilité de donnée par geo.data ? Deux datasets posent question (#788)


Bonjour @jerbou<https://github.com/jerbou>,

Les datasets pointent vers des ressources en XLS qui ne sont – malheureusement – pas reconnue avec la version actuelle de la plateforme.

Une grosse mise à jour est en cours de développement et devrait voir le jour d’ici les semaines suivantes.
Cette mise à jour permettra, entre autre, de supporter plus de types de données (XLS y compris).

Stay tuned. :)

**Comment by tusbar** [comment]
Les deux datasets sont publiés (et les fichiers xls sont désormais reconnus).
