### ISSUE TITLE
Problème de z-index pour les labels des charts

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/geo.data.gouv.fr#79]
<img width="399" alt="capture d ecran 2016-11-07 a 17 05 25" src="https://cloud.githubusercontent.com/assets/1231232/20064885/80c41b2e-a50c-11e6-9fb6-eb24b28bf076.png">

**Comment by tmerlier** [comment]
Changer le z-index semble ne donner aucun résultat. @Flightan une idée?

**Comment by Flightan** [comment]
Ca me semble logique puisque le chart est un canvas, on définit son `width` et `height` en dur, donc il ne peut pas afficher le label en entier. Je ne voit pas d'autre option qu'agrandir sa `width`, reduire la taille de la police, ou afficher `nonGeographicDat...: 40`

**Comment by tmerlier** [comment]
Changer la `width` serait plus simple et plus efficace car si le label est modifié sa légende le sera aussi.
