### ISSUE TITLE
Plus de moissonnage de Géo-IDE

### ISSUE THREAD

**Issue by rr-pro** [etalab/geo.data.gouv.fr#799]
Bonjour,
Géo-IDE n'a plus été moissonnée depuis 16 jours à en croire
https://geo.data.gouv.fr/fr/catalogs/539ebc2f1a66c51a7c52f5a3

Pouvez vous regarder ?

Merci

R Rivière

**Comment by tusbar** [comment]
Le CSW de Géo-IDE est très lent ces derniers temps : environ 1h30 pour le moissonner entièrement.

J’ai changé les timeouts à 20s par requête, et 2h max pour le moissonnage complet. Ca passe.
Vivement le nouveau point d’entrée !

https://github.com/geodatagouv/geoplatform/pull/87

Il sera dans la prochaine version de geo.data.gouv.fr qui arrive en prod dans les jours qui arrivent !

**Comment by tusbar** [comment]
Réglé : https://geo.data.gouv.fr/fr/catalogs/539ebc2f1a66c51a7c52f5a3
