### ISSUE TITLE
Page Publier des données, ajout d'un catalogue ?

### ISSUE THREAD

**Issue by jerbou** [etalab/geo.data.gouv.fr#800]
Bonjour !

Sur la page d'une organisation (DDT25), je souhaite ajouter le catalogue IDéO BFC.

https://geo.data.gouv.fr/fr/publication/559d3813c751df392b390bd4

J'aurais voulu associer cet organisation avec le catalogue idéo (en passant par ajouter un catalogue).
La page amène à des erreurs temporaires (ca peut se comprendre si on a une limitation une organisation pour un catalogue ?).

![image](https://user-images.githubusercontent.com/7600693/48191998-dffe4900-e346-11e8-9b02-61d6b715fb8b.png)

Un refresh permet de revenir, sans que l'ajout d'un nouveau catalouge soit confirmé.

est-ce que je dois au préalable supprimer le catalogue initial (géoide).

D'avance Merci,

**Comment by jerbou** [comment]
Par ailleurs, j'ai voulu supprimer le catalogue géoide, la plateforme affiche erreurs.
Peut être un pb de droit ?

**Comment by jdesboeufs** [comment]
Non je pense qu'on a un problème dans l'interface.
@tusbar tu peux jeter un oeil ? C'est quelque chose qu'on peut régler dans la prochaine version ?

**Comment by tusbar** [comment]
Bonsoir @jerbou,

Ça devrait être régler, pouvez-vous re-essayer ?

**Comment by tusbar** [comment]
Hello @jerbou,

J’ai enfin compris le problème.

Vous n’étiez qu’`editeur` de l’org DDT25 sur data.gouv.fr, je vous ai passé en `admin`, ça devrait aller mieux. :)

**Comment by jerbou** [comment]
Bonjour,

Désolé de répondre tardivement, j'ai bien pu ajouter le catalogue IDéO.
Ca va forcement mieux, avec les droits adéquats.
Merci !

**Comment by tusbar** [comment]
Parfait ! 🙌
