### ISSUE TITLE
Abbréviation Organisation et moteur de recherche datagouv

### ISSUE THREAD

**Issue by jerbou** [etalab/geo.data.gouv.fr#801]
Hello,

En mode microbug, on arrive pas à retrouver la DDT 25, en tapant cette abbréviation, alors que dans la fiche organisation 
https://www.data.gouv.fr/fr/organizations/direction-departementale-des-territoires-du-doubs/
Le sigle DDT 25 est bien saisie, mais dans la search bar de data.gouv.fr rien ne ressort.

![image](https://user-images.githubusercontent.com/7600693/48215819-5d47af00-e383-11e8-8415-d5a46c57ae4b.png)

C'est parce que l'organisation n'a pas déposé de data... C'est super stricte comme règle à l'autocomplétion ;)

A plus,

**Comment by teleboas** [comment]
Bonjour @jerbou,
Cette règle est bien volontaire et assumée, data.gouv.fr étant une plateforme dont l'objet est de diffuser des data, pas de constituer un annuaire de l'administration.
Nous vous invitons à mettre à disposition des données, nous serons ravis d'en promouvoir la diffusion.
