### ISSUE TITLE
Impossible de publier des données sur géo.data.gouv.fr

### ISSUE THREAD

**Issue by EPT12GOSB** [etalab/geo.data.gouv.fr#817]
Bonjour,

En tant qu'EPT (territoire de la métropole du Grand-Paris), nous devons publier certaines données sur géo.data.gouv.fr, mais nous sommes bloqués ...

Voici les étapes suivies sur notre compte d'organisation sur géo.data.gouv.fr : 

![image](https://user-images.githubusercontent.com/45069950/48778004-68300700-ecd4-11e8-8213-8087aad78027.png)
![image](https://user-images.githubusercontent.com/45069950/48778008-6bc38e00-ecd4-11e8-998f-f158efeba4f1.png)
![image](https://user-images.githubusercontent.com/45069950/48778015-6f571500-ecd4-11e8-9b78-a66a1becf164.png)
![image](https://user-images.githubusercontent.com/45069950/48778021-741bc900-ecd4-11e8-819b-c484d7aac05d.png)

Le jeu de données qui était coché  « Commune : métropole du grand Paris » n’apparaît pas dans :
![image](https://user-images.githubusercontent.com/45069950/48778045-7ed65e00-ecd4-11e8-890b-e2038b3dcb47.png)

Seuls les 6 jeux de données qui avaient été mis en publication le 8/11/18 apparaissent (alors que le même message «  une erreur imprévue s’est produite » apparaissait aussi le 8/11 /2018
![image](https://user-images.githubusercontent.com/45069950/48778063-8a298980-ecd4-11e8-90d2-4518ea176581.png)
De ma même manière dans mon compte dans  https://www.data.gouv.fr/fr/admin/organization/#####/  on :
-	Ne retrouve pas le jeu de donnée « Commune : métropole du grand Paris »
-	Retrouve les 6 jeux de données qui avaient été mis en publication le 8/11/18
![image](https://user-images.githubusercontent.com/45069950/48778101-9f9eb380-ecd4-11e8-9f09-9e82b0e551cd.png)
![image](https://user-images.githubusercontent.com/45069950/48778106-a5949480-ecd4-11e8-96e0-8a3facf8cd66.png)
![image](https://user-images.githubusercontent.com/45069950/48778119-acbba280-ecd4-11e8-987b-e4b16598985a.png)

Bref, nous sommes bloqués ...
Merci d'avance de votre attention et de votre aide !
Cordialement,
L'équipe SIG du Grand-Orly Seine Bièvre.

**Comment by tusbar** [comment]
Bonsoir @EPT12GOSB,

Le problème devrait être réglé, pouvez-vous re-essayer ?

Merci beaucoup.
