### ISSUE TITLE
Support de Markdown dans les descriptions

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/geo.data.gouv.fr#85]
Les producteurs utilisent de plus en plus régulièrement Markdown dans leurs descriptions.
Exemple : https://inspire.beta.gouv.fr/datasets?q=arbres

Une sous-partie devrait suffire, pour le pas polluer la hiérarchie des titres.

**Comment by jdesboeufs** [comment]
Ressources :
- https://github.com/chjj/marked
- https://github.com/evilstreak/markdown-js
- https://github.com/showdownjs/showdown

**Comment by tmerlier** [comment]
http://stackoverflow.com/questions/31875748/how-do-i-render-markdown-from-a-react-component
