### ISSUE TITLE
Is the linter working correctly?

### ISSUE THREAD

**Issue by ftonato** [etalab/geo.data.gouv.fr#850]
Hello,

Assuming that our lint is configured correctly, the code is wrong...

You can check `Circle CI` running the lint on my last _PR_ [here](https://circleci.com/gh/etalab/geo.data.gouv.fr/13189?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)!

If this make sense, can we created a new PR to fix it.
Please let me know what you do think!

**Comment by tusbar** [comment]
Hey,

Yes. the linter is configured correctly. You added an extra semicolon in your PR.
